// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuYVCUoH4vNOFy66SG2axZi4Op9lh9GC4',
    appId: '1:739995767307:web:0bf5368aa1da03041a2d0e',
    messagingSenderId: '739995767307',
    projectId: 'application-processing-center',
    authDomain: 'application-processing-center.firebaseapp.com',
    databaseURL: 'https://application-processing-center-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'application-processing-center.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2OM0NbqVYQeuAes_pNdwyAEvJJbFBJlU',
    appId: '1:739995767307:android:b9fb4228ecf01f791a2d0e',
    messagingSenderId: '739995767307',
    projectId: 'application-processing-center',
    databaseURL: 'https://application-processing-center-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'application-processing-center.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2s9hluOid_dAccW7FBamU8LBsoGvYtDU',
    appId: '1:739995767307:ios:63a672c2bb8b00661a2d0e',
    messagingSenderId: '739995767307',
    projectId: 'application-processing-center',
    databaseURL: 'https://application-processing-center-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'application-processing-center.appspot.com',
    iosBundleId: 'com.example.flutterApplicationForProcessingCenter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2s9hluOid_dAccW7FBamU8LBsoGvYtDU',
    appId: '1:739995767307:ios:3c203a98385470c91a2d0e',
    messagingSenderId: '739995767307',
    projectId: 'application-processing-center',
    databaseURL: 'https://application-processing-center-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'application-processing-center.appspot.com',
    iosBundleId: 'com.example.flutterApplicationForProcessingCenter.RunnerTests',
  );
}
